=== dueca/WorldView/vsg-viewer/vsgobjects.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://dueca.tudelft.nl"
  xmlns="https://dueca.tudelft.nl"
  elementFormDefault="qualified">

  <!-- Definition of a simple interface to vsg object mapping,
       Can be read to automatically create interpretation of current
       and new vsg factory types -->
  <xs:element name="maps">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="type" type="type_t"
          maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="type_t">
    <xs:sequence>
      <xs:element name="param" type="param_t"
        maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:simpleType name="offset_t">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="size_t">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="param_t">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="offset" type="offset_t" use="required" />
        <xs:attribute name="size" type="size_t" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== dueca/WorldView/vsg-viewer/vsgobjects.xml
<?xml version='1.0' encoding='UTF-8'?>
<maps xmlns="https://dueca.tudelft.nl"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://dueca.tudelft.nl vsgobjects.xsd">

  <type name="ambient-light">
    <param offset="0" size="3">color</param>
    <param offset="3" size="1">
      intensity
    </param>
  </type>

  <type name="directional-light">
    <param offset="0" size="3">color</param>
    <param offset="3" size="1">intensity</param>
    <param offset="4" size="3">direction</param>
  </type>

  <type name="point-light">
    <param offset="0" size="3">color</param>
    <param offset="3" size="1">intensity</param>
    <param offset="4" size="3">xyz</param>
    <param offset="7" size="1">span</param>
  </type>

  <type name="spot-light">
    <param offset="0" size="3">color</param>
    <param offset="3" size="1">intensity</param>
    <param offset="4" size="3">xyz</param>
    <param offset="7" size="1">span</param>
    <param offset="10" size="1">innerAngle</param>
    <param offset="11" size="1">outerAngle</param>
    <param offset="12" size="3">direction</param>
  </type>

  <type name="static-transform">
    <param offset="0" size="3">xyz</param>
    <param offset="3" size="3">phithetapsi</param>
    <param offset="6" size="3">scalexyz</param>
  </type>

  <type name="centered-transform">
    <param offset="0" size="3">xyz</param>
    <param offset="3" size="3">phithetapsi</param>
    <param offset="6" size="3">scalexyz</param>
  </type>


  <type name="transform">
     <param offset="0" size="3">scalexyz</param>
  </type>

  <type name="model"></type>

  <type name="static-model"></type>

</maps>
